# Generated by Django 5.2.8 on 2026-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subcategory',
        ),
    ]
